export const categories = [
    {
        id: 1,
        name: 'Banarsi Sil',
        image: '/assets/saree_model_1.png',
        description: 'The pride of Varanasi, known for gold and silver brocade.',
    },
    {
        id: 2,
        name: 'Kanjivaram',
        image: '/assets/saree_model_2.png',
        description: 'Woven from pure mulberry silk, a symbol of royalty.',
    },
    {
        id: 3,
        name: 'Patola',
        image: '/assets/cat_patola.png',
        description: 'Double ikat woven saree, usually made from silk.',
    },
    {
        id: 4,
        name: 'Chanderi',
        image: '/assets/cat_chanderi.png',
        description: 'Traditional ethnic fabric characterized by its lightweight.',
    },
    {
        id: 5,
        name: 'Saree',
        image: '/assets/saree_model_1.png',
        description: 'Elegant range of traditional and contemporary sarees.',
    },
    {
        id: 6,
        name: 'Lancha',
        image: '/assets/cat_lancha.png',
        description: 'Beautifully crafted Lanchas for weddings and festivals.',
    },
    {
        id: 7,
        name: 'Suit Piece',
        image: '/assets/cat_suit_piece.png',
        description: 'Premium unstitched suit pieces for custom tailoring.',
    },
    {
        id: 8,
        name: 'Western Gown',
        image: '/assets/cat_western_gown.png',
        description: 'Stylish western gowns for evening parties and events.',
    },
    {
        id: 9,
        name: 'Cotton Mangalagiri',
        image: '/assets/cat_mangalagiri.png',
        description: 'Durable and distinctive cotton sarees from Mangalagiri.',
    },
    {
        id: 10,
        name: 'Dharmavaram Silk',
        image: '/assets/cat_dharmavaram.png',
        description: 'Rich silk sarees with broad borders and brocade patterns.',
    },
];

export const products = [
    {
        id: 1,
        name: 'Royal Red Banarsi',
        category: 'Banarsi',
        price: 12999,
        discount: 20,
        image: '/assets/saree_model_1.png',
        images: ['/assets/saree_model_1.png', '/assets/saree_model_2.png', '/assets/hero_bg.png'],
        rating: 4.8,
    },
    {
        id: 2,
        name: 'Midnight Blue Silk',
        category: 'Silk',
        price: 8999,
        discount: 15,
        image: '/assets/saree_model_2.png',
        images: ['/assets/saree_model_2.png', '/assets/saree_model_1.png'],
        rating: 4.9,
    },
    {
        id: 3,
        name: 'Vibrant Patola Silk',
        category: 'Patola',
        price: 25000,
        discount: 10,
        image: '/assets/prod_patola_1.png',
        images: ['/assets/prod_patola_1.png', '/assets/saree_model_1.png'],
        rating: 5.0,
    },
    {
        id: 4,
        name: 'Elegant Chanderi Drape',
        category: 'Chanderi',
        price: 4500,
        discount: 0,
        image: '/assets/prod_chanderi_1.png',
        images: ['/assets/prod_chanderi_1.png', '/assets/hero_bg.png'],
        rating: 4.5,
    },
    {
        id: 5,
        name: 'Classic Silk Saree',
        category: 'Saree',
        price: 5500,
        discount: 10,
        image: '/assets/saree_model_1.png',
        images: ['/assets/saree_model_1.png', '/assets/saree_model_2.png'],
        rating: 4.6,
    },
    {
        id: 6,
        name: 'Designer Georgette Saree',
        category: 'Saree',
        price: 3800,
        discount: 5,
        image: '/assets/saree_model_2.png',
        images: ['/assets/saree_model_2.png', '/assets/saree_model_1.png'],
        rating: 4.3,
    },
    // Lancha Products
    {
        id: 7,
        name: 'Royal Red Bridal Lancha',
        category: 'Lancha',
        price: 15000,
        discount: 25,
        image: '/assets/prod_lancha_1.png',
        images: ['/assets/prod_lancha_1.png', '/assets/saree_model_2.png'],
        rating: 4.9,
    },
    {
        id: 8,
        name: 'Party Wear Pink Lancha',
        category: 'Lancha',
        price: 8500,
        discount: 15,
        image: '/assets/saree_model_2.png',
        images: ['/assets/saree_model_2.png', '/assets/prod_lancha_1.png'],
        rating: 4.7,
    },
    // Suit Piece Products
    {
        id: 9,
        name: 'Pastel Embroidered Suit',
        category: 'Suit Piece',
        price: 1200,
        discount: 0,
        image: '/assets/prod_suit_1.png',
        images: ['/assets/prod_suit_1.png', '/assets/saree_model_1.png'],
        rating: 4.2,
    },
    {
        id: 10,
        name: 'Silk Salwar Suit',
        category: 'Suit Piece',
        price: 2500,
        discount: 10,
        image: '/assets/saree_model_2.png',
        images: ['/assets/saree_model_2.png', '/assets/prod_suit_1.png'],
        rating: 4.5,
    },
    // Western Gown Products
    {
        id: 11,
        name: 'Midnight Black Evening Gown',
        category: 'Western Gown',
        price: 6500,
        discount: 20,
        image: '/assets/prod_gown_1.png',
        images: ['/assets/prod_gown_1.png', '/assets/saree_model_2.png'],
        rating: 4.8,
    },
    {
        id: 12,
        name: 'Floral Summer Gown',
        category: 'Western Gown',
        price: 4200,
        discount: 10,
        image: '/assets/saree_model_2.png',
        images: ['/assets/saree_model_2.png', '/assets/prod_gown_1.png'],
        rating: 4.4,
    },
    // New Categories Products
    {
        id: 13,
        name: 'Classic Mangalagiri Cotton',
        category: 'Cotton Mangalagiri',
        price: 2200,
        discount: 5,
        image: '/assets/prod_mangalagiri_1.png',
        images: ['/assets/prod_mangalagiri_1.png', '/assets/saree_model_1.png'],
        rating: 4.7,
    },
    {
        id: 14,
        name: 'Bridal Dharmavaram Silk',
        category: 'Dharmavaram Silk',
        price: 18000,
        discount: 15,
        image: '/assets/prod_dharmavaram_1.png',
        images: ['/assets/prod_dharmavaram_1.png', '/assets/saree_model_2.png'],
        rating: 5.0,
    },
];

export const reviews = [
    {
        id: 1,
        name: 'Aditi Sharma',
        image: '/assets/saree_model_1.png',
        email: 'aditi.s@example.com',
        comment: 'The quality of the Banarsi saree is unmatched. Felt like a queen wearing it!',
        rating: 5,
        location: 'Mumbai',
    },
    {
        id: 2,
        name: 'Priya Patel',
        image: '/assets/saree_model_2.png',
        email: 'priya.patel@example.com',
        comment: 'Beautiful collection and excellent customer service. Highly recommended.',
        rating: 5,
        location: 'Ahmedabad',
    },
    {
        id: 3,
        name: 'Sneha Gupta',
        image: '/assets/saree_model_1.png',
        email: 'sneha.gupta@example.com',
        comment: 'Authentic designs and fast delivery. Will shop again.',
        rating: 4,
        location: 'Delhi',
    },
    {
        id: 4,
        name: 'Riya Malhotra',
        image: '/assets/saree_model_2.png',
        email: 'riya.m@example.com',
        comment: 'Absolutely stunning intricate details. The silk quality is top-notch.',
        rating: 5,
        location: 'Bangalore',
    },
    {
        id: 5,
        name: 'Anjali Verma',
        image: '/assets/saree_model_1.png',
        email: 'anjali.v@example.com',
        comment: 'Perfect for my wedding trousseau. Traditional yet so classy.',
        rating: 5,
        location: 'Jaipur',
    },
    {
        id: 6,
        name: 'Meera Reddy',
        image: '/assets/saree_model_2.png',
        email: 'meera.r@example.com',
        comment: 'Love the royal blue collection. Seamless delivery experience too.',
        rating: 4,
        location: 'Hyderabad',
    },
];
